export const NISR_QUOTES = [
  {
    number: '818',
    date: 'Sep 20, 2025',
    shortTitle: 'Payment & Receivables',
    description: 'Payment Widget, Receivables Page, Job Completion Status, Formatted Report, Tax Toggle',
    days: 11,
    rate: 17,
    total: 187,
    status: 'completed',
    paymentStatus: 'paid',
    hasTimeline: true,
    hasReport: true,
  },
  {
    number: '826',
    date: 'Sep 20, 2025',
    shortTitle: 'Job Tracking & Data Integration',
    description: 'In-progress Toggle, Delayed Flag System, Inhouse & Tally Data Review, Odoo Requirements, Data Cleaning',
    days: 12,
    rate: 17,
    total: 204,
    status: 'completed',
    paymentStatus: 'paid',
    hasTimeline: true,
    hasReport: false,
  },
  {
    number: '837',
    date: 'Nov 11, 2025',
    shortTitle: 'Job Completion Certificate',
    description: 'Job Completion Certificate Status tracking for Supervisor & Office panels',
    days: 4,
    rate: 17,
    total: 68,
    status: 'completed',
    paymentStatus: 'paid',
    hasTimeline: false,
    hasReport: false,
  },
  {
    number: '916',
    date: 'Feb 3, 2026',
    shortTitle: 'Job Summary Page Revamp',
    description: 'Code revamp for Job Summary and Analysis Page with updated Google open source libraries',
    days: 3,
    rate: 17,
    total: 51,
    status: 'completed',
    paymentStatus: 'paid',
    hasTimeline: false,
    hasReport: false,
  },
  {
    number: '917',
    date: 'Feb 3, 2026',
    shortTitle: 'Full Platform Revamp',
    description: 'Job Summary, Quotation Podium, Job Order, Invoice, LPO, and Warranty page revamps',
    days: 13,
    rate: 17,
    total: 221,
    status: 'completed',
    paymentStatus: 'paid',
    hasTimeline: false,
    hasReport: false,
  },
  {
    number: '1071',
    date: 'Jun 3, 2026',
    shortTitle: 'Costing Table Enhancement',
    description: 'Adding Shipping Cost and Finance Cost columns to the costing table in the quotation system',
    days: 2,
    rate: 18,
    total: 36,
    status: 'active',
    paymentStatus: 'paid',
    hasTimeline: false,
    hasReport: false,
  },
  {
    number: '1080',
    date: 'Jun 6, 2026',
    shortTitle: 'Full AppScript Platform Revamp',
    description: 'Comprehensive revamp of all high & medium priority AppScript modules — Invoice, Job Order, Site Reports, Podium, Warranty, Tool Tracker, and more',
    days: 122,
    rate: 18,
    total: 2196,
    status: 'active',
    paymentStatus: 'partial',
    hasTimeline: false,
    hasReport: true,
  },
  {
    number: '1089',
    date: 'Jun 18, 2026',
    shortTitle: 'Post-Deadline Modifications',
    description: 'Prioritised post-deadline scope — Job Summary, Site Reports, Job Order, Warranty, Vehicle Details, OPMM — delivered in a compressed 70-day timeline, plus remaining modules free as a goodwill delivery',
    days: 70,
    rate: 26,
    total: 1818,
    status: 'active',
    paymentStatus: 'pending',
    hasTimeline: false,
    hasReport: false,
  },
];
